ozidusproject/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('', include('ozilanons.urls')),
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,document_root=settings.STATIC_ROOT)

ozilanons/urls.py
from django.urls import path
from ozilanons.views import Giris, nokulziltanimi_duzenle, Cikis, nokulziltanimi_sil, ZilListView
from ozilanons.views import index, nokulziltanimi_ekle, aokulziltanimi_ekle, ZilTanimMenu, FilteredZilListView
from ozilanons.views import ZilListViewAksam, duyurumetin_duzenle, ZilKapat, anonsduyuru_duzenle

urlpatterns = [
    path('', Giris, name='login'),
    path('home/cikis', Cikis, name='cikis'),
    path('home/', index, name='index'),
    path('home/okul/', ZilTanimMenu, name='zilayarmenu'),
    path('home/okul/odata/', ZilListView, name='zillistview'),
    path('home/okul/oadata/', ZilListViewAksam, name='zillistviewaksam'),
    path('home/okul/new/', nokulziltanimi_ekle, name='okul_new'),
    path('home/okul/aksam/new/', aokulziltanimi_ekle, name='aksam_new'),
    path('home/okul/zil/<int:ders_gun>', FilteredZilListView, name='gunzillist'),
    path('home/okul/edit/<int:id>', nokulziltanimi_duzenle, name='guncelle'),
    path('home/okul/sil/<int:id>', nokulziltanimi_sil, name='sil'),
    path('home/okul/duyurumetin/', duyurumetin_duzenle, name='duyurumetin'),
    path('home/okul/anonsduyuru/', anonsduyuru_duzenle, name='anonsduyuru'),
    path('home/okul/duyurumetin/', ZilKapat, name='zilikapat'),

]

# path('home/okul/ozilaksamdata/', AksamZilDataListView.as_view(), name='ozilaksamdata'),
# path('home/okul/ozildata/', ZilDataListView.as_view(), name='ozildata'),
# path('home/okul/anonsduyuru/', anonsduyuru, name='anonsduyuru'),
# path('home/okul/new2/', new_post_zildata, name='new2'),

uretim/models/defaultzildata.py
from django.db import models


# Create your models here.

class ZilTanimi(models.Model):
    GUN = [[0, 'Pazartesi'],
           [1, 'Salı'], [2, 'Çarşamba'],
           [3, 'Perşembe'], [4, 'Cuma'],
           [5, 'Cumartesi'],
           [6, 'Pazar'], ]

    dersbaslangicsaati = models.TimeField(verbose_name='Derslerin Başlangıç Saati', default='09:00', auto_now=False)
    toplanmasuresi = models.TimeField(verbose_name='Toplanma Süresi', default='00:10')
    ogretmenzilsuresi = models.TimeField(verbose_name='Öğretmen Ders Bildirim Zili', default='00:03')
    derssayisi = models.SmallIntegerField(verbose_name='Günlük Ders Sayısı', default=10)
    derssuresi = models.TimeField(verbose_name='Ders Süresi', default='00:40')
    tenefussuresi = models.TimeField(verbose_name='Tenefüs Süresi', default='00:10')
    oglenarasiders = models.SmallIntegerField(verbose_name='Öğlen Arası', default=6)
    oglenarasisuresi = models.TimeField(verbose_name='Öğlen Arası Süresi', default='00:45')
    zilgun = models.SmallIntegerField(verbose_name='Tanımlanan Günü', choices=GUN, default=0, unique=True)
    active = models.BooleanField(verbose_name='Aktif Pasif', default=False)
    published_date = models.DateTimeField(verbose_name='Eklenme Tarihi', auto_now_add=True)

    class Meta:
        abstract = True


class NormalOkul(ZilTanimi):

    class Meta:
        db_table = 'zildefault'
        ordering = ['zilgun']


class AksamOkul(ZilTanimi):
    class Meta:
        db_table = 'zilaksam'
        ordering = ['zilgun']


uretim/models/okulzilsaat.py
from django.db import models


# Create your models here.

class DersZamanlama(models.Model):
    GUN = [[0, 'Pazartesi'],
           [1, 'Salı'], [2, 'Çarşamba'],
           [3, 'Perşembe'], [4, 'Cuma'],
           [5, 'Cumartesi'],
           [6, 'Pazar'], ]
    okul_turu = models.CharField(max_length=100, verbose_name='Okul Türü', default='Örğün Eğitim')
    ders_gun = models.SmallIntegerField(verbose_name='Gün', choices=GUN, default=0)
    ders_no = models.SmallIntegerField(verbose_name='Ders No')
    toplanma_saati = models.TimeField(verbose_name='Toplanma Saati')
    ders_baslangic = models.TimeField(verbose_name='Dersin Başlangıç Saati')
    ogretmen_saat = models.TimeField(verbose_name='Öğretmen Bildirim Saati')
    ders_bitis = models.TimeField(verbose_name='Ders Bitiş Saati')
    active = models.BooleanField(verbose_name='Aktif Pasif', default=False)
    published_date = models.DateTimeField(verbose_name='Eklenme Tarihi', auto_now_add=True)

    class Meta:
        db_table = 'saat'
        ordering = ['ders_gun', 'ders_no', ]

    def __str__(self):
        return str(self.ders_gun)




ozilanons/forms/anons.py
from django import forms
from ozilanons.models import DuyuruData


class DuyuruDataForm(forms.ModelForm):
    class Meta:
        model = DuyuruData
        metin = forms.CharField(widget=forms.Textarea(attrs={"rows": 5, "cols": 20}))
        # fields = ('metin', 'guncellendi','zilaktif', 'mp3yolu')
        fields = ('metin',)
        exclude = ('duyurutarihi', 'id')


class ZilDurumForm(forms.ModelForm):
    class Meta:
        model = DuyuruData
        zilaktif = forms.CharField(widget=forms.CheckboxInput)
        fields = ('zilaktif',)
        exclude = ('duyurutarihi', 'id')

templates/ayarlar/anons_edit.html
{% extends 'layout/base.html' %}

{% block title %}
Duyuru
{% endblock %}

{% block top %}
{% endblock%}

{% block content %}

<body>
<form method="POST" class="post-form">
    {% csrf_token %}
    {{ form.as_p }}
    <button class="btn btn-primary btn-sm" type="submit" >Duyuru Yap</button>
</form>
</body>
{% endblock %}

{% block footer %}
{% endblock %}

templates/ayarlar/anonsduyuru.html
{% extends 'layout/base.html' %}

{% block title %}
Duyru
{% endblock %}

{% block top %}
{% endblock%}

{% block content %}
<div class="row justify-content-center vertical-center">
    <form method="POST" class="post-form">{% csrf_token %}
                <label for="id_metin"></label>
                <textarea class="form-control" name="metin" required id="id_metin" value="{{metin}}" cols="40" rows="5" ></textarea><br>
                <div class="row justify-content-center vertical-center">
                   <button class="btn btn-primary btn-sm" type="submit" >Duyuru Yap</button>
                </div>
            </form>
</div>
{% endblock %}

{% block footer %}
{% endblock %}

templates/ayarlar/ayarlar_detail.html
{% extends 'layout/base.html' %}

{% block title %}
Zil Özelleştirme
{% endblock %}


{% block top %}
{% if request.resolver_match.url_name == 'ozilaksamdata' %}
   <h4>Kayıtlı Akşam Okulu Zil Detayları</h4>
{% endif %}
{% if request.resolver_match.url_name == 'ozildata' %}
    <h4>Kayıtlı Okul Zil Detayları</h4>
{% endif %}
{% endblock%}


{% block content %}
{% load render_table from django_tables2 %}
{% render_table table %}
{% endblock %}

{% block footer %}
{% if messages %}
    {% for message in messages %}
    <div class="alert alert-{{message.tags}}">{{ message}}</div>
    {% endfor %}
{% endif %}
{% endblock %}

templates/ayarlar/gun_ds_tablosu.html
{% extends 'layout/base.html' %}

{% block title %}
Bilgileri
{% endblock %}

{% block top %}
<h6>Ayrıntlı Zil Bilgileri :

{% for  def in gundeyat %}
{% if forloop.first %}
    {{def.get_ders_gun_display}} </h6>
{% endif %}
{% endfor %}
<a class="btn btn-info btn-sm" href="{% url 'index' %}" > <<< Geri </a>
{% endblock%}

{% block content %}
<div class="table-container">
    <table class="table">
                <thead >
                    <tr>
                        <th class="orderable">
                                <a href="?sort=ders_no">Ders No</a>
                        </th>
                        <th class="orderable">
                                <a href="?sort=toplanma_saati">Toplanma</a>
                        </th>
                        <th class="orderable">
                                <a href="?sort=ders_baslangic">Öğretmen Zili</a>
                        </th>
                        <th class="orderable">
                                <a href="?sort=ogretmen_saat">Ders Zili</a>
                        </th>
                        <th class="orderable">
                                <a href="?sort=ders_bitis">Çıkış</a>
                        </th>
                        <th class="orderable">
                                <a href="?sort=active">Aktif Pasif</a>
                        </th>
                    </tr>
                </thead>
                <tbody >
                     {% for  def in gundeyat %}
                    <tr class="odd">
                            <td >{{def.ders_no}}</td>
                            <td >{{def.toplanma_saati}}</td>
                            <td >{{def.ders_baslangic}}</td>
                            <td >{{def.ogretmen_saat}}</td>
                            <td >{{def.ders_bitis}}</td>
                            <td ><span class="{{def.active}}">{% if def.active %}✔{% else %}X{% endif %}</span></td>
                    </tr>
                {% endfor %}
                </tbody>
        </table>
</div>
{% endblock %}

{% block footer %}
{% if messages %}
    {% for message in messages %}
    <div class="alert alert-{{message.tags}}">{{ message}}</div>
    {% endfor %}
{% endif %}
{% endblock %}

templates/ayarlar/index.html
{% extends 'layout/base.html' %}

{% block title %}
Ana Sayfa
{% endblock %}

{% block top %}
<h4>Aktif Zil Listesi</h4>
{% endblock%}

{% block content %}
<a class="btn btn-info btn-sm" href="{% url 'gunzillist' 0 %}">Pazartesi</a>
<a class="btn btn-info btn-sm" href="{% url 'gunzillist' 1 %}">Salı</a>
<a class="btn btn-info btn-sm" href="{% url 'gunzillist' 2 %}">Çarşamba</a>
<a class="btn btn-info btn-sm" href="{% url 'gunzillist' 3 %}">Perşembe</a>
<a class="btn btn-info btn-sm" href="{% url 'gunzillist' 4 %}">Cuma</a>
<a class="btn btn-info btn-sm" href="{% url 'gunzillist' 5 %}">Cumartesi</a>
<a class="btn btn-info btn-sm" href="{% url 'gunzillist' 6 %}">Pazar</a>
{% endblock %}

{% block footer %}
<!--<br><br>
{% if messages %}
    {% for message in messages %}
    <div class="alert alert-{{message.tags}}">{{ message}}</div>
    {% endfor %}
    {% endif %}-->
{% endblock %}

templates/ayarlar/new_ayarlar_detail.html
{% extends 'layout/base.html' %}

{% block title %}
Zil Özelleştirme
{% endblock %}


{% block top %}
{% if request.resolver_match.url_name == 'zillistviewaksam' %}
   <h4>Akşam Okulu Zil Detayları</h4>
{% endif %}
{% if request.resolver_match.url_name == 'zillistview' %}
    <h4>Örğün Eğitim Zil Detayları</h4>
{% endif %}
 <a class="btn btn-info btn-sm" href="{% url 'index' %}">Tanımlı Zili Yükle</a>
{% endblock%}
<!--{% url 'index' def.id %}-->

{% block content %}
<div class="table-container">
    <table class="table">
                <thead >
                    <tr>
                        <th class="orderable">
                                <a href="?sort=dersbaslangicsaati">Derslerin Başlangıç Saati</a>
                        </th>
                        <th class="orderable">
                                <a href="?sort=toplanmasuresi">Toplanma Süresi</a>
                        </th>
                        <th class="orderable">
                                <a href="?sort=ogretmenzilsuresi">Öğretmen Ders Bildirim Zili</a>
                        </th>
                        <th class="orderable">
                                <a href="?sort=derssayisi">Günlük Ders Sayısı</a>
                        </th>
                        <th class="orderable">
                                <a href="?sort=derssuresi">Ders Süresi</a>
                        </th>
                        <th class="orderable">
                                <a href="?sort=tenefussuresi">Tenefüs Süresi</a>
                        </th>
                        <th class="orderable">
                                <a href="?sort=oglenarasiders">Öğlen Arası</a>
                        </th>
                        <th class="orderable">
                                <a href="?sort=oglenarasisuresi">Öğlen Arası Süresi</a>
                        </th>
                        <th class="asc orderable">
                                <a href="?sort=-zilgun">Tanımlanan Günü</a>
                        </th>
                        <th class="orderable">
                                <a href="?sort=active">Aktif Pasif</a>
                        </th>
                        <th class="orderable">
                                <a href="?sort=active">İşlemler</a>
                        </th>
                    </tr>
                </thead>
                <tbody >
                     {% for  def in ziltanimi %}
                    <tr class="odd">
                            <td >{{def.dersbaslangicsaati}}</td>
                            <td >{{def.toplanmasuresi}}</td>
                            <td >{{def.ogretmenzilsuresi}}</td>
                            <td >{{def.derssayisi}}</td>
                            <td >{{def.derssuresi}}</td>
                            <td >{{def.tenefussuresi}}</td>
                            <td >{{def.oglenarasiders}}</td>
                            <td >{{def.oglenarasisuresi}}</td>
                            <td >{{def.get_zilgun_display}}</td>
                            <td ><span class="{{def.active}}">{% if def.active %}✔{% else %}X{% endif %}</span></td>
                        <td >
                            <a class="btn btn-info btn-sm" href="{% url 'guncelle' def.id %}">Düzenle</a>
                        </td>
                        <td >
                            <a class="btn btn-info btn-sm" href="{% url 'sil' def.id %}">Sil</a>
                        </td>

                    </tr>
                {% endfor %}
                </tbody>
        </table>
</div>

{% endblock %}

{% block footer %}
{% endblock %}

templates/ayarlar/post_zildata_edit.html
{% extends 'layout/base.html' %}

{% block title %}
Günün Zil Ayarları
{% endblock %}

{% block top %}
{% if request.resolver_match.url_name == 'aksam_new' %}
   <h4>Kayıtlı Akşam Okul Zil Girişi</h4>
{% endif %}
{% if request.resolver_match.url_name == 'okul_new' %}
    <h4>Kayıtlı Okul Zil Girişi</h4>
{% endif %}
{% endblock%}

{% block content %}

<form method="POST" class="post-form">{% csrf_token %}
                {{ form.as_p }}
    <button class="btn btn-primary btn-sm" type="submit" >Kaydet</button>
</form>

{% endblock %}

{% block footer %}
{% endblock %}



templates/ayarlar/zilayarmenu.html
{% extends 'layout/base.html' %}

{% block title %}
Ayarlar
{% endblock %}

{% block top %}
<nav class="mainmen">
  <ul>
    <li>Örğün Eğitim Zil Ayarları <!-- Top list level item header -->
      <ul> <!-- Sub-menu nested list -->
        <li><a href="{% url 'zillistview' %}">Zil Detayları</a></li> <!-- Second level menu item with link -->
        <li><a href="{% url 'okul_new' %}">Yeni Zil Girişi</a></li>
      </ul> <!-- End the sub-list -->
    </li> <!-- End the first top level item -->
    <li>Akşam Okulu Zil Ayarları <!-- ..and repeat -->
      <ul>
        <li><a href="{% url 'zillistviewaksam' %}">Zil Detayları</a></li>
        <li><a href="{% url 'aksam_new' %}">Yeni Zil Girişi</a></li>
      </ul>
    </li>
  <!-- and more of the same...-->
  </ul>
</nav>
{% endblock%}

{% block content %}
{% endblock %}

{% block footer %}
{% endblock %}